// astro/extractedcode/quickstart-javascript-nuxt-web/complete-application/components/LoginLink.vue
<script setup>
const { status, signIn, signOut, data } = useAuth();
</script>
<template>
  <p>
    To get started,
    <a
      @click="signIn('fusionauth', { callbackUrl: '/account' })"
      :style="{ textDecoration: 'underline', cursor: 'pointer' }"
    >
      log in or create a new account.
    </a>
  </p>
</template>

// astro/src/code-example-repositories/fusionauth-quickstart-javascript-nextjs-web-main/complete-application/src/components/LoginLink.tsx
'use client';

import { signIn } from 'next-auth/react';

export default function LoginButton({ session }: { session: any }) {
  return (
    <>
      <p>
        To get started,{' '}
        <a
          onClick={() => signIn()}
          style={{ textDecoration: 'underline', cursor: 'pointer' }}
        >
          log in or create a new account.
        </a>
      </p>
    </>
  );
}
