// astro/extractedcode/quickstart-javascript-nuxt-web/complete-application/components/LoginButton.vue
<script setup>
const { status, signIn, signOut, data } = useAuth();
</script>

<template>
  <section v-if="status === 'authenticated'">
    Status: Logged in as {{ data?.user?.email }} <br />
    <button class="button-lg" @click="signOut({ callbackUrl: '/' })">
      Log out
    </button>
  </section>
  <section v-else>
    <button
      class="button-lg"
      @click="signIn('fusionauth', { callbackUrl: '/account' })"
    >
      Log in
    </button>
  </section>
</template>

// astro/extractedcode/fusionauth-quickstart-javascript-nextjs-web/complete-application/src/components/LoginButton.tsx
'use client';

import { signIn, signOut } from 'next-auth/react';
import type { Session } from 'next-auth';

export default function LoginButton({ session }: { session: Session | null }) {
  if (session) {
    return (
      <>
        Status: Logged in as {session?.user?.email} <br />
        <button className="button-lg" onClick={() => signOut()}>
          Log out
        </button>
      </>
    );
  }
  return (
    <>
      <button className="button-lg" onClick={() => signIn()}>
        Log in
      </button>
    </>
  );
}
