// astro/extractedcode/fusionauth-quickstart-javascript-nextjs-web/complete-application/src/components/MakeChangeForm.tsx
'use client';

import { useState, type FormEvent } from 'react';

const coins = {
  quarters: 25,
  dimes: 10,
  nickels: 5,
  pennies: 1,
};

export default function MakeChangeForm() {
  const [message, setMessage] = useState('');
  const [amount, setAmount] = useState(0);

  const onMakeChange = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    try {
      setMessage('We can make change for');

      let remainingCents = Math.round(amount * 100);
      for (const [name, nominal] of Object.entries(coins)) {
        const count = Math.floor(remainingCents / nominal);
        remainingCents = remainingCents - count * nominal;

        setMessage((m) => `${m} ${count} ${name}`);
      }
      setMessage((m) => `${m}!`);
    } catch (ex: unknown) {
      const errorMessage = ex instanceof Error ? ex.message : String(ex);
      setMessage(
        `There was a problem converting the amount submitted. ${errorMessage}`
      );
    }
  };

  return (
    <section>
      <div style={{ flex: '1' }}>
        <div className="column-container">
          <div className="app-container change-container">
            <h3>We Make Change</h3>
            <div className="change-message">{message}</div>
            <form onSubmit={onMakeChange}>
              <div className="h-row">
                <div className="change-label">Amount in USD: $</div>
                <input
                  className="change-input"
                  type="number"
                  step={0.01}
                  name="amount"
                  value={amount}
                  onChange={(e) => setAmount(+e.target.value)}
                />
                <input
                  className="change-submit"
                  type="submit"
                  value="Make Change"
                />
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
}

// astro/extractedcode/quickstart-javascript-nuxt-web/complete-application/components/MakeChangeForm.vue
<script setup>
import { ref } from 'vue';

// coin values in cents, so the math stays in whole numbers
var coins = {
  quarters: 25,
  dimes: 10,
  nickels: 5,
  pennies: 1,
};

const message = ref('');
const amount = ref(0);

const onMakeChange = (event) => {
  event.preventDefault();

  try {
    message.value = 'We can make change for';

    // work in whole cents so floating-point rounding can't drop a penny
    let remainingCents = Math.round(Number(amount.value) * 100);
    for (const [name, cents] of Object.entries(coins)) {
      const count = Math.floor(remainingCents / cents);
      remainingCents -= count * cents;

      message.value = `${message.value} ${count} ${name}`;
    }
    message.value = `${message.value}!`;
  } catch (ex) {
    message.value = `There was a problem converting the amount submitted. ${ex.message}`;
  }
};
</script>
<template>
  <section>
    <div :style="{ flex: '1' }">
      <div class="column-container">
        <div class="app-container change-container">
          <h3>We Make Change</h3>
          <div class="change-message">{{ message }}</div>
          <form @submit="onMakeChange">
            <div class="h-row">
              <div class="change-label">Amount in USD: $</div>
              <input
                class="change-input"
                type="number"
                step="0.01"
                name="amount"
                :value="amount"
                @input="(event) => (amount = event.target.value)"
              />
              <input class="change-submit" type="submit" value="Make Change" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</template>
